Encoding:
  # To be safe we are leaving these files encoded ASCII-8BIT as
  # discussed at https://github.com/prawnpdf/prawn/pull/705
  Exclude:
    - lib/prawn/images/jpg.rb
    - lib/prawn/images/png.rb
    - lib/prawn/images.rb
    - spec/png_spec.rb

# These cops need to remain disabled for valid reasons on this code base

# We need to reference non-ascii characters when testing and explaining
# behavior related to win-1252, UTF-8 and UTF-16 encodings for example.
AsciiComments:
  Enabled: false

# This cops are candidates for enabling and doing the related cleanup and/or
# refactoring
Void:
  Enabled: false
StringLiterals:
  Enabled: false
HashSyntax:
  Enabled: false
UselessAssignment:
  Enabled: false
LineEndConcatenation:
  Enabled: false
SpaceAfterComma:
  Enabled: false
Lambda:
  Enabled: false
AlignHash:
  Enabled: false
LineLength:
  Enabled: false
SpaceBeforeBlockBraces:
  Enabled: false
SpaceInsideBrackets:
  Enabled: false
WordArray:
  Enabled: false
SpaceAroundEqualsInParameterDefault:
  Enabled: false
FormatString:
  Enabled: false
Blocks:
  Enabled: false
SpaceInsideBlockBraces:
  Enabled: false
CollectionMethods:
  Enabled: false
SpaceInsideHashLiteralBraces:
  Enabled: false
DotPosition:
  Enabled: false
SingleLineBlockParams:
  Enabled: false
PercentLiteralDelimiters:
  Enabled: false
SpaceInsideParens:
  Enabled: false
IfUnlessModifier:
  Enabled: false
NilComparison:
  Enabled: false
Semicolon:
  Enabled: false
Documentation:
  Enabled: false
IndentArray:
  Enabled: false
BracesAroundHashParameters:
  Enabled: false
TrailingComma:
  Enabled: false
IndentHash:
  Enabled: false
RegexpLiteral:
  Enabled: false
MethodLength:
  Enabled: false
IndentationWidth:
  Enabled: false
VariableInterpolation:
  Enabled: false
EvenOdd:
  Enabled: false
AmbiguousOperator:
  Enabled: false
SingleSpaceBeforeFirstArg:
  Enabled: false
IndentationConsistency:
  Enabled: false
AndOr:
  Enabled: false
AssignmentInCondition:
  Enabled: false
ClassAndModuleChildren:
  Enabled: false
NumericLiterals:
  Enabled: false
SignalException:
  Enabled: false
HandleExceptions:
  Enabled: false
DoubleNegation:
  Enabled: false
SelfAssignment:
  Enabled: false
Eval:
  Enabled: false
ClassLength:
  Enabled: false
ShadowingOuterLocalVariable:
  Enabled: false
TrivialAccessors:
  Enabled: false
AccessModifierIndentation:
  Enabled: false
CaseEquality:
  Enabled: false
RedundantSelf:
  Enabled: false
BlockNesting:
  Enabled: false
NegatedWhile:
  Enabled: false
MultilineIfThen:
  Enabled: false
ModuleFunction:
  Enabled: false
CyclomaticComplexity:
  Enabled: false
CaseIndentation:
  Enabled: false
UnreachableCode:
  Enabled: false
MultilineTernaryOperator:
  Enabled: false
AccessorMethodName:
  Enabled: false
SpaceAfterControlKeyword:
  Enabled: false
UselessAccessModifier:
  Enabled: false
PredicateName:
  Enabled: false
ConstantName:
  Enabled: false
UnlessElse:
  Enabled: false
MethodName:
  Enabled: false
Alias:
  Enabled: false
RedundantReturn:
  Enabled: false
DeprecatedHashMethods:
  Enabled: false
WhileUntilModifier:
  Enabled: false
StringConversionInInterpolation:
  Enabled: false
RedundantBegin:
  Enabled: false
PerlBackrefs:
  Enabled: false
CharacterLiteral:
  Enabled: false
ClassVars:
  Enabled: false
ParameterLists:
  Enabled: false
MultilineOperationIndentation:
  Enabled: false
AbcSize:
  Enabled: false
PerceivedComplexity:
  Enabled: false
UnusedBlockArgument:
  Enabled: false
UnusedMethodArgument:
  Enabled: false
Next:
  Enabled: false
ClassCheck:
  Enabled: false
SpaceBeforeComma:
  Enabled: false
StringLiteralsInInterpolation:
  Enabled: false
GuardClause:
  Enabled: false
BlockEndNewline:
  Enabled: false
