name: CI

on: push

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        gemfile:
          - Gemfile
          - Gemfile.edge
        image:
          - ruby:2.4.0
          - ruby:2.4
          - ruby:2.5.0
          - ruby:2.5
          - ruby:2.6.0
          - ruby:2.6
          - ruby:rc
          - jruby:9.2
        include:
          - image: ruby:rc
            continue-on-error: true
          - gemfile: Gemfile.edge
            continue-on-error: true
    container: ${{matrix.image}}
    steps:
      - uses: actions/checkout@v1
      - name: Set up Ruby
        run: |
          gem update --system > /dev/null
          gem --version
          gem i bundler
          bundler install --gemfile=${{matrix.gemfile}}
      - name: Run tests
        env:
          BUNDLE_GEMFILE: ${{matrix.gemfile}}
        run: bundler exec rake
      - name: Save manual
        run: |
          test -e manuals || mkdir manuals
          mv test-manual.pdf manuals/manual-$(echo -n "${{matrix.image}}" | sed 's/:/-/')-${{matrix.gemfile}}.pdf
  artifact:
    needs: test
    steps:
      - name: Upload manuals
        uses: actions/upload-artifact@v1
        with:
          name: Manual
          path: manuals
