name: CI

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby:
          - ruby:2.3.0
          - ruby:2.3
          - ruby:2.4.0
          - ruby:2.4
          - ruby:2.5.0
          - ruby:2.5
          - ruby:2.6.0
          - ruby:2.6
          - jruby:9.1.13.0
          - jruby:9.1.17.0

    container:
      image: ${{matrix.ruby}}

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: |
          gem install bundler -v '1.17.3'
          bundle install --jobs 4 --retry 3
          bundle exec rake
